db:
  username: ${username.value:postgres}
  driver: Postgres
  password: aqwsde322
  pool:
    size: 20
    timeout: 40
  properies:
    first: 123
    second: 456
    third.value: third
  url: postgres:5432
  hosts: localhost, 127.0.0.1
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 3
    - size: 3
      timeout: 3


spring:
  profiles.active: qa
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update


logging:
  level:
    root: INFO
    core.rybina.config.JpaConfiguration: INFO
    core.rybina.config: INFO
    org.springframework.jdbc.core: DEBUG
  file:
    name: ./src/main/java/core/rybina/rybina.log

